app.eureka-server: localhost

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.22.47.56:3306/cursos?serverTimezone=UTC
    username: system
    password: manager
  jpa:
    hibernate:
    naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # set the dialect  
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${random.value}"      
server:
  port: 0
---
spring.config.activate.on-profile: docker
  
app.eureka-server: eureka-server

